### ISSUE TITLE
Restrictions on content categorization

### ISSUE THREAD

**Issue by shahriaarrr** [FOSSFA/FOSSFA.github.io#11]
Your blog is currently divided into only four sections. I urge you to include categories such as (programming, technology, news and training) in your blog.

**Comment by Gnkalk** [comment]
If you use a new category, that category will be automatically added to the site :)
The use of categories such as programming is also unrestricted.

**Comment by shahriaarrr** [comment]
Ok. Thank you for your answer🙏
