### ISSUE TITLE
Bug - Failure to display correct codes in blog posts

### ISSUE THREAD

**Issue by shahriaarrr** [FOSSFA/FOSSFA.github.io#14]
If in some of the posts we use code that we have specified in the md file, such as:
```py
number = int(input("Enter your number Between 1 and 7: "))

if number == 1:
    print("shanbe")
elif number == 2:
    print("yekshanbe")
elif number == 3:
    print("Doshanbe")
elif number == 4:
    print("seshanbe")
elif number == 5:
    print("charshanbe")
elif number == 6:
    print("pangshanbe")
elif number == 7:
    print("jomee")
else:
    print("Error")
```
This part of the post is displayed in such a way that in addition to not having a beautiful appearance, it causes the code to be illegible:
![issues of FOSSFA](https://user-images.githubusercontent.com/75499598/133916517-022cf667-b7a1-4642-9d4a-d4d769468653.png)

The solution to this problem was not to specify the programming language in our code so that parts of the code would not be highlighted, but this solution is not an optimal solution and should be applied in the blog so that the code that has the highlighting of its programming language clearly To be displayed.

**Comment by Gnkalk** [comment]
Thank's You, This Bug a Fixed
